name: Cypress Tests

on:
  push:
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Instalar dependências
        run: npm install
      - name: Rodar testes Cypress
        run: npm test
